export default {
    "school": {
        text: "School Grade",
        list: [
            "Kindergarten",
            "Grade 1",
            "Grade 2",
            "Grade 3",
            "Grade 4",
            "Grade 5",
            "Grade 6",
            "Grade 7",
            "Grade 8",
        ]	
    },
    "music": {
        text: "Music",
        list: [
            "Guitar",
            "Singing",
            "Electronic",
            "Drums",
            "Jazz",
            "Beat box",
            "Harmonica",
            "Keyboard",
            "Opera",
            "Guitar",
            "Singing",
            "Electronic",
        ]
    },
    "dance": {
        text: "Dance",
        list: [
            "Freestyle",
            "Club",
            "Indian Classic",
            "Hip hop",
            "Wedding",
            "Break Dance",
            "Bollywood",
            "Salsa",
            "Ballroom",
        ]
    },
    "sport": {
        text: "Sport",
        list: [
            "Football",
            "Basketball",
            "Skating",
            "Cricket",
            "Hockey",
            "Swimming",
            "Squash",
            "Fun",
            "Cards",
            "Football",
            "Basketball",
            "Skating",
        ]
    },
    "create": {
        text: "Create",
        list: [
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
        ]
    },
    "work": {
        text: "Work",
        list: [
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
            "Lorem",
            "Ipsum",
            "Dolor",
            "Sit Amet",
            "Consectetur",
            "Adipiscing elit",
            "Sed do eiusmod",
            "Tempor",
            "Incididunt",
        ]
    },
}